### ISSUE TITLE
Swift Package cannot pass Archive Validation

### ISSUE THREAD

**Issue by djrluna** [microsoft/onnxruntime-swift-package-manager#23]
Hello,
I am using the onnx swift package in my iOS project, when attempting archive and upload a build to the TestFilght, it is failing validation with the following errors.
It appears there are two errors, the statically linked framework needs to set MinimumOSVersion in its info .plist.
Also the onnxruntime_extensions looks like it needs to renamed to not use underscores.

```
MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'MyApp.app/Frameworks/onnxruntime.framework' is ''.

Asset validation failed
Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'MyApp.app/Frameworks/onnxruntime_extensions.framework' is ''.

Asset validation failed
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle MyApp.app/Frameworks/onnxruntime.framework is required. 

Asset validation failed
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle MyApp.app/Frameworks/onnxruntime_extensions.framework is required. 

Asset validation failed
This bundle is invalid. The bundle at path Payload/Interview.app/Frameworks/onnxruntime_extensions.framework has an invalid CFBundleIdentifier 'com.microsoft.onnxruntime_extensions' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'com.microsoft.onnxruntime\u005fextensions' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105] 

Asset validation failed
Invalid Bundle. The bundle MyApp.app/Frameworks/onnxruntime.framework does not support the minimum OS Version specified in the Info.plist. 

Asset validation failed
Invalid Bundle. The bundle MyApp.app/Frameworks/onnxruntime_extensions.framework does not support the minimum OS Version specified in the Info.plist.
```

I do not get the errors when archiving and uploading using cocoa pods.
But would much rather be using Swift Packages as Onnx is the only pod being used in my project.
Thank you!

**Comment by ronyfadel** [comment]
> This bundle is invalid. The bundle at path Payload/Interview.app/Frameworks/onnxruntime_extensions.framework has an invalid CFBundleIdentifier 'com.microsoft.onnxruntime_extensions'

this one has been fixed in com.microsoft.onnxruntime_extensions

**Comment by tqtifnypmb** [comment]
> > This bundle is invalid. The bundle at path Payload/Interview.app/Frameworks/onnxruntime_extensions.framework has an invalid CFBundleIdentifier 'com.microsoft.onnxruntime_extensions'
> 
> this one has been fixed in [com.microsoft.onnxruntime_extensions](https://github.com/microsoft/onnxruntime-extensions)
> 
> cc [@edgchen1](https://github.com/edgchen1)

Should we wait for the next release, or should we just re-fetch the package?

**Comment by ronyfadel** [comment]
cc @edgchen1 @apsonawane, please, this seems like an easy fix

**Comment by edgchen1** [comment]
> this one has been fixed in [com.microsoft.onnxruntime_extensions](https://github.com/microsoft/onnxruntime-extensions)

onnxruntime-swift-package-manager 1.20.0 has been released. It uses onnxruntime-extensions 0.13.0 which includes the [fix](https://github.com/microsoft/onnxruntime-extensions/pull/834) for the invalid identifier.

**Comment by djrluna** [comment]
I still see the issue after updating to use 1.20.0 version of the package. I still see MinimumOSVersion errors when trying to validate my archive.

I think I have found a work around, but would prefer not to do this.

I added the following to Run Script under build phases and no longer see the MinimumOSVersion errors, in my case my app has a minimum iOS version of 16.0

> set -e
> /usr/libexec/PlistBuddy -c "Delete :MinimumOSVersion" "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/onnxruntime.framework/Info.plist" || true
> 
> /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string 16.0" "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/onnxruntime.framework/Info.plist"
> 
> set -e
> 
> /usr/libexec/PlistBuddy -c "Delete :MinimumOSVersion" "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/onnxruntime_extensions.framework/Info.plist" || true
> 
> /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string 16.0" "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/onnxruntime_extensions.framework/Info.plist"

**Comment by khrpnv** [comment]
Any updates on this issue?

**Comment by MilanNosal** [comment]
Any updates?

**Comment by ronyfadel** [comment]
cc @edgchen1 @apsonawane please check above comments

**Comment by rajeev-tesseractDev** [comment]
> I still see the issue after updating to use 1.20.0 version of the package. I still see MinimumOSVersion errors when trying to validate my archive.
> 
> I think I have found a work around, but would prefer not to do this.
> 
> I added the following to Run Script under build phases and no longer see the MinimumOSVersion errors, in my case my app has a minimum iOS version of 16.0
> 
> > set -e
> > /usr/libexec/PlistBuddy -c "Delete :MinimumOSVersion" "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/onnxruntime.framework/Info.plist" || true
> > /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string 16.0" "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/onnxruntime.framework/Info.plist"
> > set -e
> > /usr/libexec/PlistBuddy -c "Delete :MinimumOSVersion" "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/onnxruntime_extensions.framework/Info.plist" || true
> > /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string 16.0" "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/onnxruntime_extensions.framework/Info.plist"

I used this scrip and yet I still get the error for MinimumOSVersion on app distribution
